FROM 657399224926.dkr.ecr.us-east-1.amazonaws.com/rstudio:rbase-%%CONTAINER_VERSION%%
MAINTAINER "Milos Kozak" mkozak@finmason.com

# Install software allowing integration with base OS
RUN apt-get update && apt-get install -y \
        default-jdk \
        maven \
        git \
    && rm -rf /var/lib/apt/lists/*
